// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rclue_example_custom_msgs/msg/ExampleMsg2.msg - do not modify

#include "Msgs/ROS2ExampleMsg2.h"

#include "Kismet/GameplayStatics.h"



void UROS2ExampleMsg2Msg::Init()
{
	rclue_example_custom_msgs__msg__ExampleMsg2__init(&example_msg2_msg);
}

void UROS2ExampleMsg2Msg::Fini()
{
	rclue_example_custom_msgs__msg__ExampleMsg2__fini(&example_msg2_msg);
}

const rosidl_message_type_support_t* UROS2ExampleMsg2Msg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rclue_example_custom_msgs, msg, ExampleMsg2);
}

void UROS2ExampleMsg2Msg::SetMsg(const FROSExampleMsg2& Inputs)
{
    Inputs.SetROS2(example_msg2_msg);
}

void UROS2ExampleMsg2Msg::GetMsg(FROSExampleMsg2& Outputs) const
{
    Outputs.SetFromROS2(example_msg2_msg);
}

void* UROS2ExampleMsg2Msg::Get()
{
	return &example_msg2_msg;
}

FString UROS2ExampleMsg2Msg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}