// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rclue_example_custom_msgs/msg/ExampleMsg.msg - do not modify

#include "Msgs/ROS2ExampleMsg.h"

#include "Kismet/GameplayStatics.h"



void UROS2ExampleMsgMsg::Init()
{
	rclue_example_custom_msgs__msg__ExampleMsg__init(&example_msg_msg);
}

void UROS2ExampleMsgMsg::Fini()
{
	rclue_example_custom_msgs__msg__ExampleMsg__fini(&example_msg_msg);
}

const rosidl_message_type_support_t* UROS2ExampleMsgMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rclue_example_custom_msgs, msg, ExampleMsg);
}

void UROS2ExampleMsgMsg::SetMsg(const FROSExampleMsg& Inputs)
{
    Inputs.SetROS2(example_msg_msg);
}

void UROS2ExampleMsgMsg::GetMsg(FROSExampleMsg& Outputs) const
{
    Outputs.SetFromROS2(example_msg_msg);
}

void* UROS2ExampleMsgMsg::Get()
{
	return &example_msg_msg;
}

FString UROS2ExampleMsgMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}