// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rclue_example_custom_msgs/msg/CustomMsgExample.msg - do not modify

#include "Msgs/ROS2CustomMsgExample.h"

#include "Kismet/GameplayStatics.h"



void UROS2CustomMsgExampleMsg::Init()
{
	rclue_example_custom_msgs__msg__CustomMsgExample__init(&custom_msg_example_msg);
}

void UROS2CustomMsgExampleMsg::Fini()
{
	rclue_example_custom_msgs__msg__CustomMsgExample__fini(&custom_msg_example_msg);
}

const rosidl_message_type_support_t* UROS2CustomMsgExampleMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rclue_example_custom_msgs, msg, CustomMsgExample);
}

void UROS2CustomMsgExampleMsg::SetMsg(const FROSCustomMsgExample& Inputs)
{
    Inputs.SetROS2(custom_msg_example_msg);
}

void UROS2CustomMsgExampleMsg::GetMsg(FROSCustomMsgExample& Outputs) const
{
    Outputs.SetFromROS2(custom_msg_example_msg);
}

void* UROS2CustomMsgExampleMsg::Get()
{
	return &custom_msg_example_msg;
}

FString UROS2CustomMsgExampleMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}