// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rclue_example_custom_msgs/msg/ExampleMsg2.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rclue_example_custom_msgs/msg/example_msg2.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2ExampleMsg.h"


// Generated
#include "ROS2ExampleMsg2.generated.h"

USTRUCT(Blueprintable)
struct CUSTOMMSGEXAMPLE_API FROSExampleMsg2
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString StrField;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int IntField = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float FloatField = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSExampleMsg ExampleMsg;

	

	FROSExampleMsg2()
	{
		
	}

	void SetFromROS2(const rclue_example_custom_msgs__msg__ExampleMsg2& in_ros_data)
	{
    	StrField = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.str_field);

		IntField = in_ros_data.int_field;

		FloatField = in_ros_data.float_field;

		ExampleMsg.SetFromROS2(in_ros_data.example_msg);

		
	}

	void SetROS2(rclue_example_custom_msgs__msg__ExampleMsg2& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(StrField, out_ros_data.str_field);

		out_ros_data.int_field = IntField;

		out_ros_data.float_field = FloatField;

		ExampleMsg.SetROS2(out_ros_data.example_msg);

		
	}
};

UCLASS()
class CUSTOMMSGEXAMPLE_API UROS2ExampleMsg2Msg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSExampleMsg2& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSExampleMsg2& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rclue_example_custom_msgs__msg__ExampleMsg2 example_msg2_msg;
};