// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rclue_example_custom_msgs/msg/CustomMsgExample2.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rclue_example_custom_msgs/msg/custom_msg_example2.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2CustomMsgExample.h"


// Generated
#include "ROS2CustomMsgExample2.generated.h"

USTRUCT(Blueprintable)
struct CUSTOMMSGEXAMPLE_API FROSCustomMsgExample2
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString StrField2;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int IntField = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float FloatField = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSCustomMsgExample ExampleMsg;

	

	FROSCustomMsgExample2()
	{
		
	}

	void SetFromROS2(const rclue_example_custom_msgs__msg__CustomMsgExample2& in_ros_data)
	{
    	StrField2 = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.str_field2);

		IntField = in_ros_data.int_field;

		FloatField = in_ros_data.float_field;

		ExampleMsg.SetFromROS2(in_ros_data.example_msg);

		
	}

	void SetROS2(rclue_example_custom_msgs__msg__CustomMsgExample2& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(StrField2, out_ros_data.str_field2);

		out_ros_data.int_field = IntField;

		out_ros_data.float_field = FloatField;

		ExampleMsg.SetROS2(out_ros_data.example_msg);

		
	}
};

UCLASS()
class CUSTOMMSGEXAMPLE_API UROS2CustomMsgExample2Msg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSCustomMsgExample2& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSCustomMsgExample2& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rclue_example_custom_msgs__msg__CustomMsgExample2 custom_msg_example2_msg;
};