// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rclue_example_custom_msgs/msg/CustomMsgExample.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rclue_example_custom_msgs/msg/custom_msg_example.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2EntityState.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2CustomMsgExample.generated.h"

USTRUCT(Blueprintable)
struct CUSTOMMSGEXAMPLE_API FROSCustomMsgExample
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString StrField;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int IntField = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float FloatField = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector VectorField = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSEntityState EntitystateField;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<int> IntArrayField;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<float> FloatArrayField;

	

	FROSCustomMsgExample()
	{
		
	}

	void SetFromROS2(const rclue_example_custom_msgs__msg__CustomMsgExample& in_ros_data)
	{
    	StrField = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.str_field);

		IntField = in_ros_data.int_field;

		FloatField = in_ros_data.float_field;

		VectorField = UROS2Utils::VectorROSToUE<geometry_msgs__msg__Vector3>(in_ros_data.vector_field);

		EntitystateField.SetFromROS2(in_ros_data.entitystate_field);

		UROS2Utils::SequenceROSToUEArray<int, int>(in_ros_data.int_array_field.data, IntArrayField, in_ros_data.int_array_field.size);

		UROS2Utils::SequenceROSToUEArray<float, float>(in_ros_data.float_array_field.data, FloatArrayField, in_ros_data.float_array_field.size);

		
	}

	void SetROS2(rclue_example_custom_msgs__msg__CustomMsgExample& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(StrField, out_ros_data.str_field);

		out_ros_data.int_field = IntField;

		out_ros_data.float_field = FloatField;

		out_ros_data.vector_field = UROS2Utils::VectorUEToROS<geometry_msgs__msg__Vector3>(VectorField);

		EntitystateField.SetROS2(out_ros_data.entitystate_field);

		if (out_ros_data.int_array_field.data) {
		rosidl_runtime_c__int32__Sequence__fini(&out_ros_data.int_array_field);
		}
		if (!rosidl_runtime_c__int32__Sequence__init(&out_ros_data.int_array_field, IntArrayField.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.int_array_field  "));}
		UROS2Utils::ArrayUEToROSSequence<int, int>(IntArrayField, out_ros_data.int_array_field.data, IntArrayField.Num());

		if (out_ros_data.float_array_field.data) {
		rosidl_runtime_c__float32__Sequence__fini(&out_ros_data.float_array_field);
		}
		if (!rosidl_runtime_c__float32__Sequence__init(&out_ros_data.float_array_field, FloatArrayField.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.float_array_field  "));}
		UROS2Utils::ArrayUEToROSSequence<float, float>(FloatArrayField, out_ros_data.float_array_field.data, FloatArrayField.Num());

		
	}
};

UCLASS()
class CUSTOMMSGEXAMPLE_API UROS2CustomMsgExampleMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSCustomMsgExample& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSCustomMsgExample& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rclue_example_custom_msgs__msg__CustomMsgExample custom_msg_example_msg;
};